apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "front.fullname" . }}
  labels:
    {{- include "front.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "front.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "front.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "front.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AFFINE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.global.secret.secretName }}"
                  key: key
            - name: NODE_ENV
              value: "{{ .Values.env }}"
            - name: NODE_OPTIONS
              value: "{{ .Values.nodeOptions }}"
            - name: NO_COLOR
              value: "1"
            - name: DEPLOYMENT_TYPE
              value: "{{ .Values.global.deployment.type }}"
            - name: DEPLOYMENT_PLATFORM
              value: "{{ .Values.global.deployment.platform }}"
            - name: SERVER_FLAVOR
              value: "front"
            - name: AFFINE_ENV
              value: "{{ .Release.Namespace }}"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-postgresql
                  key: postgres-password
            - name: DATABASE_URL
              value: postgres://{{ .Values.global.database.user }}:$(DATABASE_PASSWORD)@{{ .Values.global.database.host }}:{{ .Values.global.database.port }}/{{ .Values.global.database.name }}
            - name: REDIS_SERVER_ENABLED
              value: "true"
            - name: REDIS_SERVER_HOST
              value: "{{ .Values.global.redis.host }}"
            - name: REDIS_SERVER_PORT
              value: "{{ .Values.global.redis.port }}"
            - name: REDIS_SERVER_USER
              value: "{{ .Values.global.redis.username }}"
            - name: REDIS_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: REDIS_SERVER_DATABASE
              value: "{{ .Values.global.redis.database }}"
            - name: AFFINE_INDEXER_SEARCH_PROVIDER
              value: "{{ .Values.global.indexer.provider }}"
            - name: AFFINE_INDEXER_SEARCH_ENDPOINT
              value: "{{ .Values.global.indexer.endpoint }}"
            - name: AFFINE_INDEXER_SEARCH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: indexer
                  key: indexer-apiKey
            - name: AFFINE_SERVER_PORT
              value: "{{ .Values.app.port }}"
            - name: AFFINE_SERVER_SUB_PATH
              value: "{{ .Values.app.path }}"
            - name: AFFINE_SERVER_HOST
              value: "{{- if and .Values.global.ingress.enabled (gt (len .Values.global.ingress.hosts) 0) -}}{{ index .Values.global.ingress.hosts 0 }}{{- else -}}{{ .Values.app.host }}{{- end -}}"
            - name: AFFINE_SERVER_HTTPS
              value: "{{ .Values.app.https }}"
            {{- if and .Values.global.ingress.enabled (gt (len .Values.global.ingress.hosts) 0) }}
            - name: AFFINE_SERVER_EXTERNAL_URL
              value: "{{ .Values.app.https | ternary \"https\" \"http\" }}://{{ index .Values.global.ingress.hosts 0 }}"
            - name: AFFINE_SERVER_ALLOWED_ORIGINS
              value: "{{ .Values.app.https | ternary \"https\" \"http\" }}://{{ index .Values.global.ingress.hosts 0 }}"
            {{- end }}
            - name: AFFINE_SERVER_TRUST_PROXY
              value: "{{ .Values.global.ingress.enabled | ternary \"1\" \"0\" }}"
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /info
              port: http
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
          readinessProbe:
            httpGet:
              path: /info
              port: http
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
